[package]
edition = "2021"
name = "no_heap-array-const_generic_limit-bytes-wipe_on_mut"
version = "1.0.0"
[dependencies]
utils = { path = "../00_utils" }
test_harness = { path = "../00_test_harness" }
