[package]
edition = "2021"
name = "closure-rnd-modify_any-stack-shr-arr-recurse-binary"
version = "1.0.0"
[dependencies]
utils = { path = "../00_utils" }

[dev-dependencies]
test_harness = { path = "../00_test_harness" }