[package]
edition = "2021"
name = "no_heap-bytes-own_mut-array-const_overall-limit-unsafe_str"
version = "1.0.0"
[dependencies]
utils = { path = "../00_utils" }

[dev-dependencies]
test_harness = { path = "../00_test_harness" }
