[package]
edition = "2021"
name = "no_heap-bytes-ref_mut-slice-pass_in_storage-mut_anytime"
version = "1.0.0"
[dependencies]
utils = { path = "../00_utils" }

[dev-dependencies]
test_harness = { path = "../00_test_harness" }
