[package]
edition = "2021"
name = "closure-seq-non_modify-trans-shr-ref-dyn-eq_iter_to_reentrant"
version = "1.0.0"
[dependencies]
utils = { path = "../00_utils" }

[dev-dependencies]
test_harness = { path = "../00_test_harness" }