[package]
edition = "2021"
name = "no_heap-eq_iterator_to_generic_fn"
version = "1.0.0"
[dependencies]
utils = { path = "../00_utils" }

[dev-dependencies]
test_harness = { path = "../00_test_harness" }
