# Thanks to https://github.com/prokopyl/selfie
name: Test

on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    runs-on: ubuntu-latest
    # TODO could we run checks on tests for nightly, and checks on lib sources for nightly+stable+beta?
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Format
      run: cargo fmt --all -- --check
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all --all-features -- -D warnings

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Build
      run: cargo build --all --all-features --verbose
    - name: Run tests
      run: cargo test --all --verbose
    - name: Run release tests
      run: cargo test --all --verbose --release

  miri:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 05_no_heap-array-const_limit-bytes-wipe_on_clone-unsafe
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri
      - uses: actions-rs/cargo@v1
        with:
          command: miri
          args: setup
      - uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test --all --all-features --verbose
